auth {
  fixed_users {
    enabled: true
    pass_hashed: false
    users: [
      {
        username: "visionai"
        password: "visionai_clearml_dev"
        name: "VisionAI ClearML Operator"
      }
    ]
  }
}
